blank_issues_enabled: false
contact_links:
  - name: Ticket Tracker (Jira)
    url: https://tickets.metabrainz.org/projects/BB
    about: Please open bugs here.
  - name: IRC
    url: https://bounty.github.com/
    about: "Discussion happens in #bookbrainz on IRC"
