name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
